export default [
  {
    title: 'Dashboards',
    icon: { icon: 'tabler-compass' },
    children: [
      {
        title: 'Analytics',
        to: 'dashboards-analytics',
      },
      {
        title: 'CRM',
        to: 'dashboards-crm',
      },
      {
        title: 'Ecommerce',
        to: 'dashboards-ecommerce',
      },
      {
        title: 'Academy',
        to: 'dashboards-academy',
      },
      {
        title: 'Logistics',
        to: 'dashboards-logistics',
      },
    ],
    badgeContent: '5',
    badgeClass: 'bg-error',
  },
  { heading: 'Adventures' },
  {
    title: 'All Events',
    icon: { icon: 'tabler-calendar' },
    to: 'all-events',
    action: 'read',
    subject: 'Events',
  },
  {
    title: 'Create Listing',
    icon: { icon: 'tabler-calendar-plus' },
    to: 'create-listing',
    action: 'read',
    subject: 'Listing',
  },
  {
    title: 'Add Event',
    icon: { icon: 'tabler-square-plus' },
    to: 'add-event',
    action: 'read',
    subject: 'Events',
  },
  { heading: 'Manage Bookings' },
  {
    title: 'All Bookings',
    icon: { icon: 'tabler-list-details' },
    to: 'all-bookings',
    action: 'read',
    subject: 'Bookings',
  },
  {
    title: 'Invite/Add Participants',
    icon: { icon: 'tabler-user-plus' },
    to: 'invite-participants',
    action: 'read',
    subject: 'Participants',
  },
  {
    title: 'All Participants',
    icon: { icon: 'tabler-users-plus' },
    to: 'all-participants',
    action: 'read',
    subject: 'Participants',
  },
  {
    title: 'Booking Statistics',
    icon: { icon: 'tabler-chart-bar' },
    to: 'booking-statistics',
    action: 'read',
    subject: 'Statistics',
  },
  { heading: 'Finance' },
  {
    title: 'Wallet',
    icon: { icon: 'tabler-currency-euro' },
    to: 'wallet',
    action: 'read',
    subject: 'Finance',
  },
  {
    title: 'Finance Statistics',
    icon: { icon: 'tabler-chart-bar' },
    to: 'finance-statistics',
    action: 'read',
    subject: 'Statistics',
  },
  { heading: 'Settings' },
  {
    title: 'User Profile Settings',
    icon: { icon: 'tabler-user-circle' },
    to: 'user-profile-settings',
    action: 'read',
    subject: 'Profile',
  },
  {
    title: 'Account Settings',
    icon: { icon: 'tabler-settings' },
    to: 'account-settings',
    action: 'read',
    subject: 'Settings',
  },
  {
    title: 'Get Support',
    icon: { icon: 'tabler-headphones' },
    to: 'get-support',
    action: 'read',
    subject: 'Support',
  },
] 
