-- Create auto_save_listings table
CREATE TABLE IF NOT EXISTS auto_save_listings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    listing_type VARCHAR(255) DEFAULT 'single-date',
    status VARCHAR(255) DEFAULT 'on_process',
    form_data JSON,
    packages JSON NULL,
    special_addons JSON NULL,
    itinerary JSON NULL,
    periods JSON NULL,
    adventure_title VARCHAR(255) NULL,
    description TEXT NULL,
    location VARCHAR(255) NULL,
    price DECIMAL(10,2) NULL,
    min_capacity INT NULL,
    max_capacity INT NULL,
    group_language VARCHAR(255) NULL,
    experience_level VARCHAR(255) NULL,
    fitness_level VARCHAR(255) NULL,
    activities_included JSON NULL,
    maps_and_routes JSON NULL,
    listing_media JSON NULL,
    promotional_video JSON NULL,
    whats_included TEXT NULL,
    whats_not_included TEXT NULL,
    additional_notes TEXT NULL,
    providers_faq TEXT NULL,
    personal_policies TEXT NULL,
    starting_date VARCHAR(255) NULL,
    finishing_date VARCHAR(255) NULL,
    min_advance_notice VARCHAR(255) NULL,
    max_advance_booking VARCHAR(255) NULL,
    available_days JSON NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_status (user_id, status),
    INDEX idx_created_at (created_at)
);
